export default {
  login: 'trannguyenvu3482',
  id: 87817412,
  node_id: 'MDQ6VXNlcjg3ODE3NDEy',
  avatar_url: 'https://avatars.githubusercontent.com/u/87817412?v=4',
  gravatar_id: '',
  url: 'https://api.github.com/users/trannguyenvu3482',
  html_url: 'https://github.com/trannguyenvu3482',
  followers_url: 'https://api.github.com/users/trannguyenvu3482/followers',
  following_url:
    'https://api.github.com/users/trannguyenvu3482/following{/other_user}',
  gists_url: 'https://api.github.com/users/trannguyenvu3482/gists{/gist_id}',
  starred_url:
    'https://api.github.com/users/trannguyenvu3482/starred{/owner}{/repo}',
  subscriptions_url:
    'https://api.github.com/users/trannguyenvu3482/subscriptions',
  organizations_url: 'https://api.github.com/users/trannguyenvu3482/orgs',
  repos_url: 'https://api.github.com/users/trannguyenvu3482/repos',
  events_url: 'https://api.github.com/users/trannguyenvu3482/events{/privacy}',
  received_events_url:
    'https://api.github.com/users/trannguyenvu3482/received_events',
  type: 'User',
  site_admin: false,
  name: 'Vu Tran',
  company: 'Industrial University of HCMC',
  blog: 'https://linktr.ee/trannguyenvu3482',
  location: 'Ho Chi Minh, Vietnam',
  email: null,
  hireable: null,
  bio: 'A front-end web developer from HCMC, Vietnam',
  twitter_username: null,
  public_repos: 13,
  public_gists: 0,
  followers: 0,
  following: 0,
  created_at: '2021-07-22T13:55:01Z',
  updated_at: '2022-04-15T13:51:41Z',
};
